
wallets:
  ['Phantom', 'Keplr', 'Metamask', 'Sui', 'Total']

phantom:
  run_meteora: True
  ticker_coingecko: ['MOCKJUP', 'CWIF', 'GM', 'ROCK']


keplr:


metamask:
  ticker_coingecko: ['RSWETH']

sui:




