#the maximum number of coingecko tokens is 6

wallets:
  ['Phantom', 'Keplr', 'Metamask', 'Sui', 'OKX', 'Total']
metrics:
  ['Portfolio value', 'Absolute ROI', 'PnL day', 'Rewards']

phantom:
  run_meteora: True
  ticker_coingecko: ['MOCKJUP', 'CWIF', 'IQ50', 'ROCK']


keplr:
  ticker_coingecko: ['STTIA']

metamask:
  ticker_coingecko: ['RSWETH']

sui:
  ticker_coingecko: []

okx:
  ticker_coingecko: []





